## @file AppleModulePkg.dsc
#
# 
#
# Copyright (C) 2005 - 2015 Apple Inc. All rights reserved.
#
# This program and the accompanying materials have not been licensed.
# Neither is its usage, its redistribution, in source or binary form,
# licensed, nor implicitely or explicitely permitted, except when
# required by applicable law.
#
# Unless required by applicable law or agreed to in writing, software
# distributed is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.
#
#  
##

[Defines]
  PLATFORM_NAME             = AppleModule
  PLATFORM_GUID             = 0ADCC78E-2FDC-4491-998D-8684A7B602E9
  PLATFORM_VERSION          = 2015-001
  DSC_SPECIFICATION         = 0x00010006
  OUTPUT_DIRECTORY          = Build/$(PLATFORM_NAME)
  SUPPORTED_ARCHITECTURES   = IA32|IPF|X64|EBC|ARM|AARCH64
  BUILD_TARGETS             = RELEASE|DEBUG
  SKUID_IDENTIFIER          = DEFAULT
  EFI_SPECIFICATION_VERSION = 0x0001000A
  PI_SPECIFICATION_VERSION  = 0x00000009
  TIANO_RELEASE_VERSION     = 0x00080006

[LibraryClasses]
  #
  # EDK
  #
  EfiDriverLib|EdkCompatibilityPkg/Foundation/Library/Dxe/EfiDriverLib/EfiDriverLib_Edk2.inf
  EdkProtocolLib|EdkCompatibilityPkg/Foundation/Protocol/EdkProtocolLib.inf
  EdkFrameworkGuidLib|EdkCompatibilityPkg/Foundation/Framework/Guid/EdkFrameworkGuidLib.inf
  EfiCommonLib|EdkBridgePkg/Library/EfiCommonLib/EfiCommonLib_Edk2.inf
  EfiProtocolLib|EdkCompatibilityPkg/Foundation/Efi/Protocol/EfiProtocolLib.inf
  EdkGuidLib|EdkCompatibilityPkg/Foundation/Guid/EdkGuidLib.inf
  EdkFrameworkProtocolLib|EdkCompatibilityPkg/Foundation/Framework/Protocol/EdkFrameworkProtocolLib.inf
  UefiEfiIfrSupportLib|EdkCompatibilityPkg/Foundation/Library/Dxe/UefiEfiIfrSupportLib/UefiEfiIfrSupportLib.inf

  #
  # Apple
  #
  AppleDriverLib|ApplePkg/Library/AppleDriverLib/AppleDriverLib.inf
  AppleKeyMapAggregatorLib|ApplePkg/Library/AppleKeyMapAggregatorLib/AppleKeyMapAggregatorLib.inf
  AppleKeyMapLib|ApplePkg/Library/AppleKeyMapLib/AppleKeyMapLib.inf
  AppleMathLib|ApplePkg/Library/AppleMathLib/AppleMathLib.inf
  AppleSmcMmioLib|ApplePkg/Library/AppleSmcMmioLib/AppleSmcMmioLib.inf
  MmioLib|ApplePkg/Library/BaseMmioLib/BaseMmioLib.inf
  UsbDxeLib|ApplePkg/Library/UsbDxeLib/UsbDxeLib.inf

  #
  # Apple protocol implementations
  #
  AppleEventImpl|AppleModulePkg/Protocol/AppleEventImpl/AppleEventImpl.inf
  AppleBootPolicyImpl|AppleModulePkg/Protocol/AppleBootPolicyImpl/AppleBootPolicyImpl.inf
  AppleKeyMapImpl|AppleModulePkg/Protocol/AppleKeyMapImpl/AppleKeyMapImpl.inf
  ApplePlatformInfoDatabaseImpl|AppleModulePkg/Protocol/ApplePlatformInfoDatabaseImpl/ApplePlatformInfoDatabaseImpl.inf
  AppleSmcIoImpl|AppleModulePkg/Protocol/AppleSmcIoImpl/AppleSmcIoImpl.inf
  EfiDevicePathPropertyDatabaseImpl|AppleModulePkg/Protocol/DevicePathPropertyDatabaseImpl/DevicePathPropertyDatabaseImpl.inf
  EfiKeyboardInformationImpl|AppleModulePkg/Protocol/KeyboardInformationImpl/KeyboardInformationImpl.inf
  EfiOsIdentificationImpl|AppleModulePkg/Protocol/OsIdentificationImpl/OsIdentificationImpl.inf

[LibraryClasses.IA32, LibraryClasses.X64]
  NULL|EdkCompatibilityPkg/Foundation/Library/CompilerStub/CompilerStubLib_Edk2.inf

[LibraryClasses.ARM, LibraryClasses.AARCH64]
  #
  # It is not possible to prevent ARM compiler calls to generic intrinsic functions.
  # This library provides the instrinsic functions generated by a given compiler.
  # [LibraryClasses.ARM] and NULL mean link this library into all ARM images.
  #
  NULL|ArmPkg/Library/CompilerIntrinsicsLib/CompilerIntrinsicsLib.inf

[Components]
  AppleModulePkg/Protocol/AppleEventImpl/AppleEventImpl.inf
  AppleModulePkg/Protocol/AppleBootPolicyImpl/AppleBootPolicyImpl.inf
  AppleModulePkg/Protocol/AppleKeyMapImpl/AppleKeyMapImpl.inf
  AppleModulePkg/Protocol/ApplePlatformInfoDatabaseImpl/ApplePlatformInfoDatabaseImpl.inf
  AppleModulePkg/Protocol/DevicePathPropertyDatabaseImpl/DevicePathPropertyDatabaseImpl.inf
  AppleModulePkg/Protocol/OsIdentificationImpl/OsIdentificationImpl.inf

  AppleModulePkg/Driver/AppleBootPolicy/AppleBootPolicy.inf
  AppleModulePkg/Driver/AppleEvent/AppleEvent.inf
  AppleModulePkg/Driver/AppleKeyMapAggregator/AppleKeyMapAggregator.inf
  AppleModulePkg/Driver/AppleOsIdentification/AppleOsIdentification.inf
  AppleModulePkg/Driver/ApplePlatformInfoDB/ApplePlatformInfoDB.inf
  AppleModulePkg/Driver/AppleSmcIo/AppleSmcIo.inf
  AppleModulePkg/Driver/EfiDevicePathPropertyDatabase/EfiDevicePathPropertyDatabase.inf
  AppleModulePkg/Driver/UsbKb/UsbKb.inf

[BuildOptions]
DEFINE MSFT_MACRO  = /D EFI_SPECIFICATION_VERSION=$(EFI_SPECIFICATION_VERSION) /D PI_SPECIFICATION_VERSION=$(PI_SPECIFICATION_VERSION) /D TIANO_RELEASE_VERSION=$(TIANO_RELEASE_VERSION)
DEFINE INTEL_MACRO = /D EFI_SPECIFICATION_VERSION=$(EFI_SPECIFICATION_VERSION) /D PI_SPECIFICATION_VERSION=$(PI_SPECIFICATION_VERSION) /D TIANO_RELEASE_VERSION=$(TIANO_RELEASE_VERSION)
DEFINE GCC_MACRO   = -DEFI_SPECIFICATION_VERSION=$(EFI_SPECIFICATION_VERSION) -DPI_SPECIFICATION_VERSION=$(PI_SPECIFICATION_VERSION) -DTIANO_RELEASE_VERSION=$(TIANO_RELEASE_VERSION) -DNO_BUILTIN_VA_FUNCS -fno-stack-protector -Wno-unused-but-set-variable
DEFINE XCODE_MACRO = -DEFI_SPECIFICATION_VERSION=$(EFI_SPECIFICATION_VERSION) -DPI_SPECIFICATION_VERSION=$(PI_SPECIFICATION_VERSION) -DTIANO_RELEASE_VERSION=$(TIANO_RELEASE_VERSION)

  INTEL:DEBUG_*_*_CC_FLAGS   = $(INTEL_MACRO) /D EFI_DEBUG
  INTEL:RELEASE_*_*_CC_FLAGS = $(INTEL_MACRO) /D EFI_NDEBUG /D MDEPKG_NDEBUG
  GCC:DEBUG_*_*_CC_FLAGS     = $(GCC_MACRO) -DEFI_DEBUG
  GCC:RELEASE_*_*_CC_FLAGS   = $(GCC_MACRO) -DEFI_NDEBUG -DMDEPKG_NDEBUG
  MSFT:DEBUG_*_*_CC_FLAGS    = $(MSFT_MACRO) /D EFI_DEBUG
  MSFT:RELEASE_*_*_CC_FLAGS  = $(MSFT_MACRO) /D EFI_NDEBUG /D MDEPKG_NDEBUG
  XCODE:DEBUG_*_*_CC_FLAGS   = $(XCODE_MACRO) -DEFI_DEBUG
  XCODE:RELEASE_*_*_CC_FLAGS = $(XCODE_MACRO) -DEFI_NDEBUG -DMDEPKG_NDEBUG
