## @file
# Copyright (C) 2005 - 2015, Apple Inc.  All rights reserved.<BR>
#
# This program and the accompanying materials have not been licensed.
# Neither is its usage, its redistribution, in source or binary form,
# licensed, nor implicitely or explicitely permitted, except when
# required by applicable law.
#
# Unless required by applicable law or agreed to in writing, software
# distributed is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied.
#
#  
##

[Defines]
  PLATFORM_NAME             = AppleModule
  PLATFORM_GUID             = 0ADCC78E-2FDC-4491-998D-8684A7B602E9
  PLATFORM_VERSION          = 2015-001
  DSC_SPECIFICATION         = 0x00010006
  OUTPUT_DIRECTORY          = Build/$(PLATFORM_NAME)
  SUPPORTED_ARCHITECTURES   = IA32|IPF|X64|EBC|ARM|AARCH64
  BUILD_TARGETS             = RELEASE|DEBUG
  SKUID_IDENTIFIER          = DEFAULT
  EFI_SPECIFICATION_VERSION = 0x0001000A
  PI_SPECIFICATION_VERSION  = 0x00000009
  TIANO_RELEASE_VERSION     = 0x00080006

[LibraryClasses]
  # EDK

  EfiDriverLib|EdkCompatibilityPkg/Foundation/Library/Dxe/EfiDriverLib/EfiDriverLib_Edk2.inf
  EdkProtocolLib|EdkCompatibilityPkg/Foundation/Protocol/EdkProtocolLib.inf
  EdkFrameworkGuidLib|EdkCompatibilityPkg/Foundation/Framework/Guid/EdkFrameworkGuidLib.inf
  EfiCommonLib|EdkBridgePkg/Library/EfiCommonLib/EfiCommonLib_Edk2.inf
  EfiProtocolLib|EdkCompatibilityPkg/Foundation/Efi/Protocol/EfiProtocolLib.inf
  EdkGuidLib|EdkBridgePkg/Guid/EdkGuidLib/EdkGuidLib.inf 
  EdkFrameworkProtocolLib|EdkCompatibilityPkg/Foundation/Framework/Protocol/EdkFrameworkProtocolLib.inf
  UefiEfiIfrSupportLib|EdkCompatibilityPkg/Foundation/Library/Dxe/UefiEfiIfrSupportLib/UefiEfiIfrSupportLib.inf

  # Apple

  AppleDriverLib|AppleModulePkg/Library/AppleDriverLib/AppleDriverLib.inf
  AppleKeyMapAggregatorLib|AppleModulePkg/Library/AppleKeyMapAggregatorLib/AppleKeyMapAggregatorLib.inf
  AppleKeyMapLib|AppleModulePkg/Library/AppleKeyMapLib/AppleKeyMapLib.inf
  AppleMathLib|AppleModulePkg/Library/AppleMathLib/AppleMathLib.inf
  AppleSmcMmioLib|AppleModulePkg/Library/AppleSmcMmioLib/AppleSmcMmioLib.inf
  MmioLib|AppleModulePkg/Library/BaseMmioLib/BaseMmioLib.inf
  UsbDxeLib|AppleModulePkg/Library/UsbDxeLib/UsbDxeLib.inf

  # Apple protocol implementations

  AppleEventImpl|AppleModulePkg/Protocol/AppleEventImpl/AppleEventImpl.inf
  AppleBootPolicyImpl|AppleModulePkg/Protocol/AppleBootPolicyImpl/AppleBootPolicyImpl.inf
  AppleKeyMapImpl|AppleModulePkg/Protocol/AppleKeyMapImpl/AppleKeyMapImpl.inf
  ApplePlatformInfoDatabaseImpl|AppleModulePkg/Protocol/ApplePlatformInfoDatabaseImpl/ApplePlatformInfoDatabaseImpl.inf
  AppleSmcIoImpl|AppleModulePkg/Protocol/AppleSmcIoImpl/AppleSmcIoImpl.inf
  EfiDevicePathPropertyDatabaseImpl|AppleModulePkg/Protocol/DevicePathPropertyDatabaseImpl/DevicePathPropertyDatabaseImpl.inf
  EfiKeyboardInformationImpl|AppleModulePkg/Protocol/KeyboardInformationImpl/KeyboardInformationImpl.inf
  EfiOsIdentificationImpl|AppleModulePkg/Protocol/OsIdentificationImpl/OsIdentificationImpl.inf

[LibraryClasses.IA32, LibraryClasses.X64]
  NULL|EdkCompatibilityPkg/Foundation/Library/CompilerStub/CompilerStubLib_Edk2.inf

[LibraryClasses.ARM, LibraryClasses.AARCH64]
  # It is not possible to prevent ARM compiler calls to generic intrinsic functions.
  # This library provides the instrinsic functions generated by a given compiler.
  # [LibraryClasses.ARM] and NULL mean link this library into all ARM images.
  NULL|ArmPkg/Library/CompilerIntrinsicsLib/CompilerIntrinsicsLib.inf

[Components]
  AppleModulePkg/Library/AppleDriverLib/AppleDriverLib.inf
  AppleModulePkg/Library/BaseMmioLib/BaseMmioLib.inf
  AppleModulePkg/Library/AppleKeyMapLib/AppleKeyMapLib.inf
  AppleModulePkg/Library/AppleKeyMapAggregatorLib/AppleKeyMapAggregatorLib.inf
  AppleModulePkg/Library/AppleMathLib/AppleMathLib.inf
  AppleModulePkg/Library/AppleSmcMmioLib/AppleSmcMmioLib.inf
  AppleModulePkg/Library/UsbDxeLib/UsbDxeLib.inf

  AppleModulePkg/Protocol/AppleEventImpl/AppleEventImpl.inf
  AppleModulePkg/Protocol/AppleBootPolicyImpl/AppleBootPolicyImpl.inf
  AppleModulePkg/Protocol/AppleKeyMapImpl/AppleKeyMapImpl.inf
  AppleModulePkg/Protocol/ApplePlatformInfoDatabaseImpl/ApplePlatformInfoDatabaseImpl.inf
  AppleModulePkg/Protocol/DevicePathPropertyDatabaseImpl/DevicePathPropertyDatabaseImpl.inf
  AppleModulePkg/Protocol/OsIdentificationImpl/OsIdentificationImpl.inf

  AppleModulePkg/Driver/AppleBootPolicy/AppleBootPolicy.inf
  AppleModulePkg/Driver/AppleEvent/AppleEvent.inf
  AppleModulePkg/Driver/AppleKeyMapAggregator/AppleKeyMapAggregator.inf
  AppleModulePkg/Driver/AppleOsIdentification/AppleOsIdentification.inf
  AppleModulePkg/Driver/ApplePlatformInfoDB/ApplePlatformInfoDB.inf
  AppleModulePkg/Driver/AppleSmcIo/AppleSmcIo.inf
  AppleModulePkg/Driver/EfiDevicePathPropertyDatabase/EfiDevicePathPropertyDatabase.inf
  AppleModulePkg/Driver/UsbKb/UsbKb.inf

[BuildOptions]

# General build options

DEFINE SLASH_MACRO = /D EFI_SPECIFICATION_VERSION=$(EFI_SPECIFICATION_VERSION) /D PI_SPECIFICATION_VERSION=$(PI_SPECIFICATION_VERSION) /D TIANO_RELEASE_VERSION=$(TIANO_RELEASE_VERSION)
DEFINE DASH_MACRO  = -DEFI_SPECIFICATION_VERSION=$(EFI_SPECIFICATION_VERSION) -DPI_SPECIFICATION_VERSION=$(PI_SPECIFICATION_VERSION) -DTIANO_RELEASE_VERSION=$(TIANO_RELEASE_VERSION)

  INTEL:DEBUG_*_*_CC_FLAGS   = $(SLASH_MACRO) /D EFI_DEBUG
  INTEL:RELEASE_*_*_CC_FLAGS = $(SLASH_MACRO) /D EFI_NDEBUG /D MDEPKG_NDEBUG
  GCC:DEBUG_*_*_CC_FLAGS     = $(DASH_MACRO) -DEFI_DEBUG
  GCC:RELEASE_*_*_CC_FLAGS   = $(DASH_MACRO) -DEFI_NDEBUG -DMDEPKG_NDEBUG
  MSFT:DEBUG_*_*_CC_FLAGS    = $(SLASH_MACRO) /D EFI_DEBUG
  MSFT:RELEASE_*_*_CC_FLAGS  = $(SLASH_MACRO) /D EFI_NDEBUG /D MDEPKG_NDEBUG
  XCODE:DEBUG_*_*_CC_FLAGS   = $(DASH_MACRO) -DEFI_DEBUG
  XCODE:RELEASE_*_*_CC_FLAGS = $(DASH_MACRO) -DEFI_NDEBUG -DMDEPKG_NDEBUG

  # Disable errors

  GCC:*_GCC46_*_CC_FLAGS = -Wno-error=unused-but-set-parameter -Wno-error=unused-but-set-variable
  GCC:*_GCC47_*_CC_FLAGS = -Wno-error=unused-but-set-parameter -Wno-error=unused-but-set-variable
  GCC:*_GCC48_*_CC_FLAGS = -Wno-error=unused-but-set-parameter -Wno-error=unused-but-set-variable
  GCC:*_GCC49_*_CC_FLAGS = -Wno-error=unused-but-set-parameter -Wno-error=unused-but-set-variable

  # Disable breaking features

  GCC:*_GCC44_ARM_CC_FLAGS = -fno-stack-protector
  GCC:*_GCC45_ARM_CC_FLAGS = -fno-stack-protector
  GCC:*_GCC46_ARM_CC_FLAGS = -fno-stack-protector
  GCC:*_GCC47_ARM_CC_FLAGS = -fno-stack-protector
  GCC:*_GCC48_ARM_CC_FLAGS = -fno-stack-protector
  GCC:*_GCC49_ARM_CC_FLAGS = -fno-stack-protector

  # Expose EDK architecture
  
  # IA32

  INTEL:*_*_IA32_CC_FLAGS    = /D EFI32
  INTEL:*_*_IA32_ASM_FLAGS   = /DEFI32
  INTEL:*_*_IA32_VFRPP_FLAGS = /D EFI32
  INTEL:*_*_IA32_APP_FLAGS   = /D EFI32
  INTEL:*_*_IA32_PP_FLAGS    = /D EFI32

  GCC:*_*_IA32_CC_FLAGS    = -DEFI32
  GCC:*_*_IA32_VFRPP_FLAGS = -DEFI32
  GCC:*_*_IA32_APP_FLAGS   = -DEFI32
  GCC:*_*_IA32_PP_FLAGS    = -DEFI32

  MSFT:*_*_IA32_CC_FLAGS    = /D EFI32
  MSFT:*_*_IA32_ASM_FLAGS   = /DEFI32
  MSFT:*_*_IA32_VFRPP_FLAGS = /D EFI32
  MSFT:*_*_IA32_APP_FLAGS   = /D EFI32
  MSFT:*_*_IA32_PP_FLAGS    = /D EFI32

  XCODE:*_*_IA32_CC_FLAGS    = -DEFI32
  XCODE:*_*_IA32_VFRPP_FLAGS = -DEFI32
  XCODE:*_*_IA32_APP_FLAGS   = -DEFI32
  XCODE:*_*_IA32_PP_FLAGS    = -DEFI32

  # X64

  INTEL:*_*_X64_CC_FLAGS    = /D EFIX64
  INTEL:*_*_X64_ASM_FLAGS   = /DEFIX64
  INTEL:*_*_X64_VFRPP_FLAGS = /D EFIX64
  INTEL:*_*_X64_APP_FLAGS   = /D EFIX64
  INTEL:*_*_X64_PP_FLAGS    = /D EFIX64

  GCC:*_*_X64_CC_FLAGS    = -DEFIX64
  GCC:*_*_X64_VFRPP_FLAGS = -DEFIX64
  GCC:*_*_X64_APP_FLAGS   = -DEFIX64
  GCC:*_*_X64_PP_FLAGS    = -DEFIX64

  MSFT:*_*_X64_CC_FLAGS    = /D EFIX64
  MSFT:*_*_X64_ASM_FLAGS   = /DEFIX64
  MSFT:*_*_X64_VFRPP_FLAGS = /D EFIX64
  MSFT:*_*_X64_APP_FLAGS   = /D EFIX64
  MSFT:*_*_X64_PP_FLAGS    = /D EFIX64

  XCODE:*_*_X64_CC_FLAGS    = -DEFIX64
  XCODE:*_*_X64_VFRPP_FLAGS = -DEFIX64
  XCODE:*_*_X64_APP_FLAGS   = -DEFIX64
  XCODE:*_*_X64_PP_FLAGS    = -DEFIX64

  # IPF

  INTEL:*_*_IPF_CC_FLAGS    = /D EFI64
  INTEL:*_*_IPF_ASM_FLAGS   = /DEFI64
  INTEL:*_*_IPF_VFRPP_FLAGS = /D EFI64
  INTEL:*_*_IPF_APP_FLAGS   = /D EFI64
  INTEL:*_*_IPF_PP_FLAGS    = /D EFI64

  GCC:*_*_IPF_CC_FLAGS    = -DEFI64
  GCC:*_*_IPF_VFRPP_FLAGS = -DEFI64
  GCC:*_*_IPF_APP_FLAGS   = -DEFI64
  GCC:*_*_IPF_PP_FLAGS    = -DEFI64

  MSFT:*_*_IPF_CC_FLAGS    = /D EFI64
  MSFT:*_*_IPF_ASM_FLAGS   = /DEFI64
  MSFT:*_*_IPF_VFRPP_FLAGS = /D EFI64
  MSFT:*_*_IPF_APP_FLAGS   = /D EFI64
  MSFT:*_*_IPF_PP_FLAGS    = /D EFI64

  # ARM

  GCC:*_*_ARM_CC_FLAGS    = -DEFIARM
  GCC:*_*_ARM_VFRPP_FLAGS = -DEFIARM
  GCC:*_*_ARM_APP_FLAGS   = -DEFIARM
  GCC:*_*_ARM_PP_FLAGS    = -DEFIARM

  RVCT:*_*_ARM_CC_FLAGS    = -DEFIARM
  RVCT:*_*_ARM_VFRPP_FLAGS = -DEFIARM
  RVCT:*_*_ARM_APP_FLAGS   = -DEFIARM
  RVCT:*_*_ARM_PP_FLAGS    = -DEFIARM

  # AARCH64

  GCC:*_*_AARCH64_CC_FLAGS    = -DEFIAARCH64 -DEFIARM
  GCC:*_*_AARCH64_VFRPP_FLAGS = -DEFIAARCH64 -DEFIARM
  GCC:*_*_AARCH64_APP_FLAGS   = -DEFIAARCH64 -DEFIARM
  GCC:*_*_AARCH64_PP_FLAGS    = -DEFIAARCH64 -DEFIARM
